# Generated by Django 5.0.4 on 2024-05-16 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListRetraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('titre', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{8}$', 'Le titre doit contenir 8 caractères alphanumériques.')])),
                ('beneficiaire', models.CharField(max_length=255)),
                ('nni', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Le NNI doit contenir exactement 10 chiffres.')])),
                ('date_retraite', models.DateField()),
                ('ville', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('telephone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
