# Generated by Django 5.0.4 on 2024-05-16 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0002_operationretraite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listretraite',
            name='beneficiaire',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listretraite',
            name='nni',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Le NNI doit contenir exactement 10 chiffres.')]),
        ),
    ]
