# Generated by Django 5.0.4 on 2024-05-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0003_alter_listretraite_beneficiaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationretraite',
            name='list_retraite',
        ),
    ]
