# Generated by Django 5.0.4 on 2024-05-17 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0006_operateretraite_beneficiaire_operateretraite_nni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operateretraite',
            old_name='list_retraite',
            new_name='titre_list_retraite',
        ),
        migrations.RemoveField(
            model_name='listretraite',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='operateretraite',
            name='ordre',
        ),
    ]
