# Generated by Django 5.0.4 on 2024-05-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0007_rename_list_retraite_operateretraite_titre_list_retraite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operateretraite',
            old_name='titre_list_retraite',
            new_name='Numero_titre',
        ),
    ]
