# Generated by Django 5.0.4 on 2024-05-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0008_rename_titre_list_retraite_operateretraite_numero_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateretraite',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
