# Generated by Django 5.0.4 on 2024-05-18 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0009_operateretraite_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operateretraite',
            options={'ordering': ['-date_operation']},
        ),
        migrations.RemoveField(
            model_name='operateretraite',
            name='order',
        ),
    ]
