# Generated by Django 5.0.4 on 2024-05-26 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0010_alter_operateretraite_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listretraite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='operateretraite',
            name='ordre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operateretraite',
            name='Numero_titre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppChefAgence.listretraite'),
        ),
    ]
