# Generated by Django 5.0.4 on 2024-06-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0012_alter_listretraite_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listretraite',
            name='ordre',
        ),
    ]
