# Generated by Django 5.0.4 on 2024-06-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0014_listretraite_ordre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listretraite',
            name='ordre',
        ),
    ]
