# Generated by Django 5.0.4 on 2024-06-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0015_remove_listretraite_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='listretraite',
            name='ordre',
            field=models.IntegerField(null=True),
        ),
    ]
