# Generated by Django 5.0.4 on 2024-06-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0017_alter_listretraite_ordre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listretraite',
            old_name='ordre',
            new_name='ordre_enregistrement',
        ),
    ]
