# Generated by Django 5.0.4 on 2024-06-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChefAgence', '0019_remove_operateretraite_ordre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operateretraite',
            name='ordre_enregistrement',
        ),
        migrations.AddField(
            model_name='operateretraite',
            name='ordre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listretraite',
            name='ordre_enregistrement',
            field=models.IntegerField(default=0),
        ),
    ]
